spring:
  datasource:
    url: jdbc:oracle:thin:@bh1bb19a0xop0l3r_high?TNS_ADMIN=src/main/resources/wallet
    username: TESTE
    password: "@Tar77429012"
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSourceImpl
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      connection-pool-name: ADBExample
      initial-pool-size: 5
      min-pool-size: 1
      max-pool-size: 30
      shared: true

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
