spring:
  jpa:
    show-sql: true
  application:
    name: solarmetrics
  profiles:
    active: ${PROFILE:local}
  rabbitmq:
    virtual-host: email
    password: admin
    username: admin
    port: 5672
resend:
  api-key: re_b2iLCwmQ_ioMQnKpmy3fGb7NHxi1zNd1V